[project]
name = "Intelligent-data-cleaner-v1.0"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-core>=0.3.0",
    "langchain-google-genai>=2.0.0",
    "numpy==1.26.4",
    "openpyxl==3.1.2",
    "pandas==2.2.0",
    "plotly==5.18.0",
    "pydantic>=2.0",
    "python-dotenv>=1.0.0",
    "pyyaml==6.0.1",
    "rich==13.7.0",
    "scikit-learn==1.4.0",
    "scipy==1.12.0",
    "streamlit==1.31.0",
]
